[package]
name = "url"
version = "0.2.0"
authors = ["Wataru Matsui <watawuwu@3bi.tech>"]
edition = "2018"

[dependencies]
percent-encoding = "2.1"
anyhow = "1.0"
structopt = "0.3"
atty = "0.2"
log = "0.4"
pretty_env_logger = "0.4"
